# Generated by Django 5.0.2 on 2024-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=2100),
        ),
    ]
